spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/simplelibrary
    username: simplelibrary
    password: simplelibrary
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
